version: '3.9'
services: 
  cbs-flaskapp:
   image: cbs-flask:uniappv1
   build:
     context: . #location of dockerfile
     dockerfile: Dockerfile
   container_name: cbspyc1
   ports:
   - 4980:5000

  #above steps have merging build and run